projects:
  carforum:
    schemaPath: amplify/backend/api/carforum/build/schema.graphql
    includes:
      - App.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-west-1
        apiId: null
        maxDepth: 2
